# Generated by Django 4.1.5 on 2023-02-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Курс")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="image/", verbose_name="Превью"
                    ),
                ),
                ("description", models.TextField(verbose_name="Содержание курса")),
            ],
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы",},
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Урок")),
                ("description", models.TextField(verbose_name="Содержание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="image/", verbose_name="Превью"
                    ),
                ),
                ("video", models.URLField(blank=True, null=True, verbose_name="Видео")),
                (
                    "crss",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                        verbose_name="Урок курса",
                    ),
                ),
            ],
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки",},
        ),
    ]
